### ISSUE TITLE
Host Directory

### ISSUE THREAD

**Issue by psullivan6** [registerguard/drone#6]
Where should the image and potentially other assets live? static? advertising? new subdomain?

**Comment by mhulse** [comment]
> Where should the image and potentially other assets live? static? advertising? new subdomain?

For each 3rd party?

Part of me wonders if each 3rd party would have it's own copy of the theme? In other words, we'd create repos with the 3rd party as a sub module? Is that overkill?

In other words, each 3rd party would probably have it's own collection of assets, so it would make a little sense to collect it all in the same location.

I guess the bigger question is, should we think of this theme as a sub module to other things, or just treat it as a centralized bit of code that get linked to for the various 3rd parties?

It's hard for me to think this through because I don't have a current project that needs to use this yet. I was kinda thinking that I'd be able to have more thoughts if I were to apply Drone to something in the real world.

So, what could I do over here in the news dept. that could use the new 3rd party look/feel? Maybe stats hosted? I just have a huge list of things I'm trying to tackle without going crazy.

I'd say, for now, host all of your 3rd party assets on advertising whilst keeping in mind:
1. File issues for any ideas for improvements and/or workflows
2. Things will change in coming weeks (sorry), so you'll probably have to refactor your stetup just a tad as the theme improves and we figure out exactly how this is going to work.
3. Other?

**Comment by mhulse** [comment]
The other part of this theme is: What parts of the base styles should be included and what parts of the css should be pulled from, potentially, bulldog (once that's be divided into two parts).

For example, I feel like Drone needs to have a good set of base styles (like p tags and link colors) ... A lot of these things will be a part of the future bulldog build.

Just mentioning because that might be direction we head, so it might affect what you do now. Just wanted you to keep that in mind.

I really need to get the bulldog/dreamliner/raptor project completed, as I think it will help the work that's being done with Drone theme.

Then again, are we making things too complicated? That's a concern I have too.

**Comment by mhulse** [comment]
Keep in mind, I have yet to do any 3rd parties using new look/feel, so some of the below thoughts may change after I've had a chance to do some real world work.
1. For "skins" or "child themes" I was planning on create repositories based on Drone (as a submodule). Once the theme had been completed, I would clone it to http://static.registerguard.com and then link to the assets (CSS/JS/IMG) from the 3rd party.
2. Same could be said for non-3rd parties. Hosting the "theme" or "skin" on static, and then linking absolutely to the assets.
3. If I have a PHP project, I'll separate the skin from the PHP files (and probably create repos for both, one being a drone child theme) so I can independently work on either piece of code.
4. I'm not a fan of global assets in the sense that I arbitrarily link to said assets. It's one thing if I have a theme that's in version control and hosted on static.registerguard.com where I'm using said theme for multiple projects and have a [simple tracking system like Bulldog's](https://github.com/registerguard/bulldog/wiki). It's another (bad) thing if I just put random files somewhere and link to them as I see fit (take for example the old static.rg.com setup; I had put a ton of JS files there and linked to them for various projects without any tracking ... I've been kicking myself in the butt every day since, after I realized that was a bad idea).
   1. An exception to the rule would be fonts. We use fonts.registerguard.com for any fonts, and it's probably best to host all font assets there (this is mostly due to the fact that certain browsers have security restrictions and the server setup needs to have a somewhat unique setup to host fonts).
5. **Question:** Based on the above thoughts, should we host child themes on both ad.rg.com and static.rg.com? Or, just on static.rg.com? What would you prefer?
6. Based on all the above, **what do you think?**

**Comment by psullivan6** [comment]
All sounds good and I agree!

Seems like hosting `raptor` at a higher-level directory on advertising is the way to go and then just absolutely link to it, whereas drone and other smaller repo stuff can just be per project as you mentioned.

As for **5.** I would think putting the assets in the project directory would work best and that directory can differ depending on its scope

Let me know if these thoughts seem off-track :smile:

**Comment by mhulse** [comment]
> Seems like hosting `raptor` at a higher-level directory on advertising is the way to go and then just absolutely link to it, whereas drone and other smaller repo stuff can just be per project as you mentioned.

Hard for me to give productive feedback as I haven't really been introduced to your setup (IMHO, I think your headed in right direction though). Additionally, my only experience is with Bulldog, so I have yet work with themes as submodules. :frowning:

In general though, for me (not to beat a dead horse horse), I try to avoid random linking of assets.

Take Bulldog for example. I have Bulldog repo hosted on static, and absolutely link to assets via the templates of the various server-side technologies ... My [super basic tracking system](https://github.com/registerguard/bulldog/wiki) makes it (hopefully) easy for folks to know where things live and how to update them (in the case of Bulldog, I just have to change one variable, on each system, in order to update the templates to the latest build).

Boring broken record alert!!!!

I try to build things as if I wasn't going to be the one to maintain them. In other words, how easy would it be for someone to follow in my footsteps. Sure, Grunt (for example) has a little bit of a learning curve if you've not used it before, but that's when I [point to our WIKI](https://github.com/registerguard/registerguard.github.com/wiki) with Grunt setup tutorials.

From there, once one has learned how to do a build, then it's just a matter of knowing how, and where, to update the template's theme's build version.

Maybe, if we follow rules of thumb, like:
1. How easy would it be for someone to follow in your footsteps (as John calls it "hit by a bus" OR "abducted by aliens" OR "you might go work for the UO athletic dept." (last one means dead to us, not technically dead and/or inaccessible) tests)?
2. Are you tracking what systems are linking to your assets/themes/templates?
3. Other?

... then we should be golden!

> As for **5.** I would think putting the assets in the project directory would work best and that directory can differ depending on its scope

Yah, that sounds logical to me. :smile:

**Comment by psullivan6** [comment]
Sweet. Closing based on consensus reached :+1:
